default: &default
  adapter: postgresql
  url: <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>

production:
  primary:
    <<: *default
  cable:
    <<: *default
    url: <%= ENV.fetch("DATABASE_CABLE_URL", ENV["DATABASE_URL"]) %>
    migrations_paths: db/cable_migrate
  queue:
    <<: *default
    url: <%= ENV.fetch("DATABASE_QUEUE_URL", ENV["DATABASE_URL"]) %>
    migrations_paths: db/queue_migrate
  cache:
    <<: *default
    url: <%= ENV.fetch("DATABASE_CACHE_URL", ENV["DATABASE_URL"]) %>
    migrations_paths: db/cache_migrate
